# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"path_data": "NER_tagging.ipynb",
         "CoNLL03DatasetReader": "NER_tagging.ipynb"}

modules = ["conll_reader.py"]

doc_url = "https://Tom Roth.github.io/tagger/"

git_url = "https://github.com/Tom Roth/tagger/tree/master/"

def custom_doc_links(name): return None
